In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("/content/x_learner_training.csv")

In [3]:
DISCOUNT_COST = 100
AVG_REVENUE = 1000

In [5]:
df.columns

Index(['customerID', 'gender', 'SeniorCitizen', 'Partner', 'Dependents',
       'tenure', 'PhoneService', 'MultipleLines', 'InternetService',
       'OnlineSecurity', 'OnlineBackup', 'DeviceProtection', 'TechSupport',
       'StreamingTV', 'StreamingMovies', 'Contract', 'PaperlessBilling',
       'PaymentMethod', 'MonthlyCharges', 'TotalCharges', 'Churn',
       'TenureBucket', 'FamilyIndicator', 'SupportBundle', 'StreamingBundle',
       'Treatment_Prob', 'Treatment', 'TreatmentEffect', 'BaseProb',
       'TreatedProb', 'Y0', 'Y1', 'Outcome', 'uplift_pred', 'segment'],
      dtype='object')

In [6]:
df["expected_gain"] = df["uplift_pred"] * AVG_REVENUE
df["roi"] = df["expected_gain"] - DISCOUNT_COST

In [7]:
total_profit = df["roi"].sum()
print(total_profit)

566193.4414103996

In [8]:
df.groupby("segment")["roi"].mean()

segment
Persuadable      145.043484
Sleeping Dogs     35.649382
Sure Things     -177.155563
Name: roi, dtype: float64

In [9]:
df[df["roi"] > 0].sort_values("roi", ascending=False)

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,TreatmentEffect,BaseProb,TreatedProb,Y0,Y1,Outcome,uplift_pred,segment,expected_gain,roi
3271,3902-FOIGH,Male,1,Yes,No,12,Yes,Yes,Fiber optic,No,...,0.47,0.60,0.13,0,1,0,0.407149,Persuadable,407.148906,307.148906
628,2469-DTSGX,Female,1,No,No,72,Yes,Yes,Fiber optic,No,...,0.37,0.30,0.01,0,1,0,0.396807,Persuadable,396.807332,296.807332
4875,2302-ANTDP,Female,1,Yes,No,48,Yes,Yes,Fiber optic,Yes,...,0.37,0.50,0.13,0,0,0,0.392184,Persuadable,392.183878,292.183878
2448,9221-OTIVJ,Female,1,No,No,14,Yes,Yes,Fiber optic,No,...,0.47,0.60,0.13,0,1,0,0.389952,Persuadable,389.951626,289.951626
6562,3621-CEOVK,Female,1,Yes,No,14,Yes,Yes,Fiber optic,No,...,0.47,0.60,0.13,1,1,1,0.382343,Persuadable,382.343209,282.343209
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6132,3896-RCYYE,Female,0,No,No,67,No,No phone service,DSL,No,...,0.10,0.25,0.15,1,1,1,0.100332,Sleeping Dogs,100.331793,0.331793
6890,7470-DYNOE,Male,0,No,No,53,Yes,No,DSL,No,...,0.10,0.05,0.01,1,1,1,0.100331,Sleeping Dogs,100.330572,0.330572
3651,2900-PHPLN,Female,1,Yes,No,70,Yes,No,No,No internet service,...,0.25,0.15,0.01,1,1,1,0.100135,Sleeping Dogs,100.135137,0.135137
1219,2294-DMMUS,Female,0,Yes,Yes,62,Yes,Yes,DSL,No,...,0.10,0.25,0.15,1,0,0,0.100094,Sleeping Dogs,100.093806,0.093806
5132,3850-OKINF,Male,0,Yes,Yes,71,Yes,Yes,DSL,Yes,...,0.10,0.05,0.01,1,1,1,0.100045,Sleeping Dogs,100.044520,0.044520

In [11]:
def decision(uplift):
    if uplift > 0.2:
        return "Offer Discount"
    elif uplift > 0:
        return "Low Priority Offer"
    else:
        return "Do Not Target"

In [12]:
df["Decision"] = df["uplift_pred"].apply(decision)

In [14]:
df.to_csv("customer_cate_predictions.csv", index=False)